# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    serializer: ~
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        product:
            persistence:
                driver: orm
                model: App\Entity\Product
                provider: ~
                finder: ~
            properties:
                name: ~
                description: ~
            serializer:
                groups: [product]
